document.querySelector("#button").addEventListener("click", () => {
    backgroundchange();
});
backgroundchange = ()=>{
    var back=[   "url('https://wallpapercave.com/wpt/wp4099125.jpg')",
    "url('https://wallpapercave.com/wpt/wp4091452.jpg')",
    "url('https://wallpapercave.com/wpt/wp3888391.jpg')",
    "url('https://wallpapercave.com/wpt/wp4091912.jpg')",
    "url('https://wallpapercave.com/wpt/2ddplhM.jpg')", 
    "url('https://wallpapercave.com/wpt/wp3904340.png')",
    "url('https://wallpapercave.com/wpt/D5t2Xce.jpg')", 
    "url('https://wallpapercave.com/wpt/wp3585378.jpg')",
    "url('https://wallpapercave.com/wpt/wp1993659.jpg')",
    "url('https://wallpapercave.com/wpt/wp2700770.jpg')",
    "url('https://wallpapercave.com/wpt/wp1900340.png')",
    "url('https://wallpapercave.com/wpt/wp2284078.jpg')",
    "url('https://wallpapercave.com/wpt/jgj6Feb.jpg')", 
    "url('https://wallpapercave.com/wpt/wp1872038.png')",
    "url('https://wallpapercave.com/wpt/wp2172664.jpg')",
    "url('https://wallpapercave.com/wpt/wp1891962.jpg')",
    "url('https://wallpapercave.com/wpt/q63WjmJ.jpg')", 
    "url('https://wallpapercave.com/wpt/jJYOGTC.jpg')", 
    "url('https://wallpapercave.com/wpt/wp3904343.jpg')",
    "url('https://wallpapercave.com/wpt/wp1891963.jpg')",
    "url('https://wallpapercave.com/wpt/wp4092120.jpg')",
    "url('https://wallpapercave.com/wpt/ORy33o6.jpg')", 
    "url('https://wallpapercave.com/wpt/wp2119475.png')",
    "url('https://wallpapercave.com/wpt/yU5c9ae.jpg')", 
    "url('https://wallpapercave.com/wpt/wp2212329.jpg')",
    "url('https://wallpapercave.com/wpt/wp2640663.png')",
    "url('https://wallpapercave.com/wpt/wp4091627.jpg')",
    "url('https://wallpapercave.com/wpt/wp2510144.jpg')",
    "url('https://wallpapercave.com/wpt/wp4091254.jpg')",
    "url('https://wallpapercave.com/wpt/wp4089170.jpg')",
    "url('https://wallpapercave.com/wpt/wp4088469.png')",
    "url('https://wallpapercave.com/wpt/wp2349755.jpg')",
    "url('https://wallpapercave.com/wpt/Ra2Q10Y.jpg')", 
    "url('https://wallpapercave.com/wpt/wp4091019.png')",
    "url('https://wallpapercave.com/wpt/wp1892131.png')",
    "url('https://wallpapercave.com/wpt/wp1833521.jpg')",
    "url('https://wallpapercave.com/wpt/wp2538946.jpg')",
    "url('https://wallpapercave.com/wpt/wp4089323.jpg')",
    "url('https://wallpapercave.com/wpt/wp4089833.jpg')",
    "url('https://wallpapercave.com/wpt/LvgYwAb.jpg')", 
    "url('https://wallpapercave.com/wpt/wp4090904.jpg')",
    "url('https://wallpapercave.com/wpt/wp4088551.jpg')",
    "url('https://wallpapercave.com/wpt/wp4089405.jpg')",
    "url('https://wallpapercave.com/wpt/wp4089534.jpg')",
    "url('https://wallpapercave.com/wpt/wp3968871.jpg')",
    "url('https://wallpapercave.com/wpt/wp1809894.jpg')",
    "url('https://wallpapercave.com/wpt/wp4091878.png')",
    "url('https://wallpapercave.com/wpt/wp4089712.png')",
    "url('https://wallpapercave.com/wpt/wp4088349.jpg')",
    "url('https://wallpapercave.com/wpt/wp4088092.jpg')",
    "url('https://wallpapercave.com/wpt/wp3754604.jpg')",
    "url('https://wallpapercave.com/wpt/wp4091669.jpg')",
    "url('https://wallpapercave.com/wpt/wp4089588.png')",
    "url('https://wallpapercave.com/wpt/NG9RfqR.jpg')", 
    "url('https://wallpapercave.com/wpt/wp4090987.jpg')",
    "url('https://wallpapercave.com/wpt/wp4092502.jpg')",
    "url('https://wallpapercave.com/wpt/wp4088033.jpg')",
    "url('https://wallpapercave.com/wpt/wp4089282.jpg')",
    "url('https://wallpapercave.com/wpt/wp4091840.jpg')",
    "url('https://wallpapercave.com/wpt/wp2435989.png')",
    "url('https://wallpapercave.com/wpt/wp4091562.jpg')",
    "url('https://wallpapercave.com/wpt/qXrvHA3.jpg')", 
    "url('https://wallpapercave.com/wpt/wp1853119.png')",
    "url('https://wallpapercave.com/wpt/wp1837539.jpg')",
    "url('https://wallpapercave.com/wpt/wp2020594.jpg')",
    "url('https://wallpapercave.com/wpt/wp4099646.jpg')",
    "url('https://wallpapercave.com/wpt/wp1874038.png')",
    "url('https://wallpapercave.com/wpt/wp4091907.jpg')",
    "url('https://wallpapercave.com/wpt/lwBUEp9.jpg')", 
    "url('https://wallpapercave.com/wpt/J4cPdF5.jpg')", 
    "url('https://wallpapercave.com/wpt/65iJjjo.jpg')", 
    "url('https://wallpapercave.com/wpt/sq92SMf.jpg')", 
    "url('https://wallpapercave.com/wpt/wp4091138.jpg')",
    "url('https://wallpapercave.com/wpt/6UaIpB1.jpg')", 
    "url('https://wallpapercave.com/wpt/wp3904341.jpg')",
    "url('https://wallpapercave.com/wpt/wp3899869.jpg')",
    "url('https://wallpapercave.com/wpt/6gQoQWB.jpg')", 
    "url('https://wallpapercave.com/wpt/wp1976726.png')",
    "url('https://wallpapercave.com/wpt/tOswykL.jpg')", 
    "url('https://wallpapercave.com/wpt/wp1838977.jpg')",
    "url('https://wallpapercave.com/wpt/Q2qHwkC.jpg')", 
    "url('https://wallpapercave.com/wpt/wp4088339.jpg')",
    "url('https://wallpapercave.com/wpt/wp4088157.jpg')",
    "url('https://wallpapercave.com/wpt/wp4153504.png')",
    "url('https://wallpapercave.com/wpt/wp2390524.jpg')",
    "url('https://wallpapercave.com/wpt/wp4153643.jpg')",
    "url('https://wallpapercave.com/wpt/wp2200978.png')",
    "url('https://wallpapercave.com/wpt/wp4099218.jpg')",
    "url('https://wallpapercave.com/wpt/wp1848061.png')",
    "url('https://wallpapercave.com/wpt/wp4091785.jpg')",
    "url('https://wallpapercave.com/wpt/wxAty5s.png')", 
    "url('https://wallpapercave.com/wpt/wp4092360.jpg')",
    "url('https://wallpapercave.com/wpt/wp1959331.png')",
    "url('https://wallpapercave.com/wpt/wp4091310.jpg')",
    "url('https://wallpapercave.com/wpt/SVkG5hW.jpg')", 
    "url('https://wallpapercave.com/wpt/wp4089188.jpg')",
    "url('https://wallpapercave.com/wpt/wp1894643.jpg')",
    "url('https://wallpapercave.com/wpt/MsDREkd.jpg')", 
    "url('https://wallpapercave.com/wpt/wp4099525.jpg')",
    "url('https://wallpapercave.com/wpt/wp4089440.jpg')",
    "url('https://wallpapercave.com/wpt/RTSWhxx.jpg')", 
    "url('https://wallpapercave.com/wpt/wp1809893.jpg')",
    "url('https://wallpapercave.com/wpt/wp4091116.png')",
    "url('https://wallpapercave.com/wpt/wp4099258.jpg')",
    "url('https://wallpapercave.com/wpt/wp1860707.png')",
    "url('https://wallpapercave.com/wpt/wp4092859.png')",
    "url('https://wallpapercave.com/wpt/wp2538497.jpg')",
    "url('https://wallpapercave.com/wpt/wp4099483.jpg')",
    "url('https://wallpapercave.com/wpt/wp1858907.png')",
    "url('https://wallpapercave.com/wpt/wp4099342.jpg')",
    "url('https://wallpapercave.com/wpt/wp1871171.png')",
    "url('https://wallpapercave.com/wpt/wp4091493.jpg')",
    "url('https://wallpapercave.com/wpt/wp3192477.jpg')",
    "url('https://wallpapercave.com/wpt/wp3951101.png')",
    "url('https://wallpapercave.com/wpt/wp3963518.png')",
    "url('https://wallpapercave.com/wpt/wp1812452.png')",
    "url('https://wallpapercave.com/wpt/wp3856064.jpg')",
    "url('https://wallpapercave.com/wpt/wp4089617.png')",
    "url('https://wallpapercave.com/wpt/wp2172674.png')",
    "url('https://wallpapercave.com/wpt/wp1848044.jpg')",
    "url('https://wallpapercave.com/wpt/wp1937304.png')",
    "url('https://wallpapercave.com/wpt/wp3882445.jpg')",
    "url('https://wallpapercave.com/wpt/wp1837539.jpg')",
    "url('https://wallpapercave.com/wpt/wp4741012.jpg')",
    "url('https://wallpapercave.com/wpt/wp4828513.jpg')",
    "url('https://wallpapercave.com/wpt/wp5137079.png')",
    "url('https://wallpapercave.com/wpt/wp4673891.png')",
    "url('https://wallpapercave.com/wpt/wp1818245.png')",
    "url('https://wallpapercave.com/wpt/wp4734306.jpg')",
    "url('https://wallpapercave.com/wpt/wp4684324.jpg')",
    "url('https://wallpapercave.com/wpt/wp4734369.jpg')",
    "url('https://wallpapercave.com/wpt/wp1916852.jpg')",
    "url('https://wallpapercave.com/wpt/wp3951102.jpg')",
]
    const random = back[Math.floor(Math.random() * back.length)];
    console.log(random);
    document.body.style.backgroundImage =random;
}

document.querySelector("#generate").addEventListener("click", () => {
  generate();
});

generate = () => {
  fetch("'https://animechan.xyz/api/random'")
    .then((response) => response.json())
    .then((data) => {
        let list= data;
        //console.log(list);
        //console.log(list.anime);
        quote.innerHTML=`<p>${list.quote}</p>
        <h3>by~ ${list.character}</h3>
        <h4>Anime~ ${list.anime}</h4>`
    })
    

};
